package com.nuzhnov.workcontrol.shared.visitservice.domen.model

enum class VisitControlServiceStopReason {
    TECHNOLOGY_UNSUPPORTED_ERROR,
    TECHNOLOGY_DISABLED_ERROR,
    PERMISSION_DENIED_ERROR,
    DISCONNECTED_ERROR,
    INIT_ERROR,
    MAX_ACCEPT_CONNECTION_ATTEMPTS_REACHED,
    IO_ERROR,
    SECURITY_ERROR,
    UNKNOWN_ERROR,
    SERVICE_DESTROYED
}
